const inventoryTabText = {
  zh: {
    importOverwrite: '匯入後將覆蓋現有紀錄，是否繼續？',
    importDone: '已匯入完成',
    exportCsvConfirm: '確定要匯出 CSV？',
    backupPrompt: '距離上次備份已超過30天，是否匯出 CSV 備份？',
    inputRequired: '請輸入完整資料',
    invalidNumbers: '請輸入有效數字、價格和日期',
    confirmDeleteRecord: '確定要刪除此筆紀錄？',
    sellExceeds: '賣出數量不得超過庫存',
    notice: '這是一個免費網站，我們不會把你的資料存到任何後台或伺服器。為確保使用者隱私，所有的紀錄（包含你的設定與操作歷程）都只會保存在你的瀏覽器本機。開啟自動儲存功能後，系統會在你的裝置上自動備份。簡單說：資料只在這台電腦，不會上傳，也不會被我們看到，請安心使用！',
    addRecord: '新增購買',
    quickAdd: '快速購買',
    quickAddEmpty: '目前沒有最近購買的 ETF',
    quickAddTitle: '快速新增購買紀錄',
    quickAddNoPurchase: '購買',
    quickAddDate: '購買日期',
    quickAddQuantity: '購買數量',
    quickAddPrice: '購買價格',
    quickAddSave: '儲存',
    quickAddClose: '關閉',
    quickAddSelectionSummary: '已勾選 {count} 檔 ETF',
    quickAddCurrencyTwd: 'NT$',
    quickAddCurrencyUsd: 'US$',
    quickAddPlaceholderQuantity: '請輸入數量',
    quickAddPlaceholderPrice: '請輸入價格',
    dataAccess: '存取資料',
    currentInventory: '目前庫存',
    showHistory: '顯示：交易歷史',
    cache: '快取',
    stockCache: '股票清單快取',
    dividendCache: '股息資料快取',
    totalInvestment: '總投資金額：',
    totalValue: '目前總價值：',
    investmentGoals: '預期的股息目標',
    goalNameLabel: '幫目標取個名字',
    goalNamePlaceholder: '例：一年滾出 10 萬股息',
    goalNameHelper: '清楚的名稱能提醒自己為什麼開始。',
    goalFormIntro: '替你的股息計畫取個名字，選擇年度、每月或最低目標，讓努力更有方向！',
    goalCurrencyLabel: '目標幣別',
    goalCurrencyTwd: '台幣（NT$）',
    goalCurrencyUsd: '美金（US$）',
    goalCashflowSectionTitle: '現金流目標',
    goalCashflowEmpty: '還沒有設定現金流目標，按「新增現金流目標」開始。',
    goalCashflowAdd: '新增現金流目標',
    goalCashflowRemove: '移除目標',
    goalTypeLabel: '選擇目標類型',
    annualGoal: '年度目標',
    monthlyGoal: '月平均目標',
    minimumGoal: '每月最低目標',
    goalDividendAccumulated: '累積股息：',
    goalDividendMonthly: '每月平均股息：',
    goalDividendMinimum: '每月最低股息：',
    goalTargetAnnual: '年度目標：',
    goalTargetMonthly: '月平均目標：',
    goalTargetMinimum: '每月最低目標：',
    goalText: '我的計畫',
    goalSave: '儲存',
    goalSaved: '已儲存，加油！',
    goalSavedEmpty: '趕快設下你的目標吧！',
    goalEmpty: '還沒設定股息計畫？給目標取個響亮的名字，再填上年度與每月數字吧！',
    goalInputPlaceholderTotal: '例：50000',
    goalInputPlaceholderMonthly: '例：5000',
    goalFormShow: '設定或更新目標',
    goalFormHide: '收起設定',
    goalAnnualHalf: '年度進度過半，離夢想更近一步！',
    goalAnnualDone: '恭喜完成年度目標，繼續打造現金流！',
    goalMonthlyHalf: '這個月過半囉，再衝一把！',
    goalMinimumHalf: '每月最低過半囉，再衝一把！',
    goalMonthlyDone: '月目標達成，保持這個節奏！',
    goalMinimumDone: '月最低目標達成，保持這個節奏！',
    goalDividendYtdLabel: '累積股息',
    goalDividendAnnualLabel: '年度股息',
    goalDividendMonthlyLabel: '每月平均股息',
    goalDividendMinimumLabel: '每月最低股息',
    goalAchievementLabel: '達成率',
    shareGoalSectionTitle: '存股張數目標',
    shareGoalEmptyList: '還沒有設定存股目標，輸入代碼與目標張數後按下「新增存股目標」。',
    shareGoalStockInputLabel: '股票代碼 / 名稱',
    shareGoalStockInputPlaceholder: '例：0056 高股息ETF',
    shareGoalTargetLabelForm: '目標張數',
    shareGoalTargetPlaceholder: '例：100',
    shareGoalAddButton: '新增存股目標',
    shareGoalRemove: '移除',
    shareGoalUnit: '張',
    shareGoalCurrent: '目前張數：',
    shareGoalTargetDisplay: '目標張數：',
    shareGoalHalf: '進度過半，再加把勁！',
    shareGoalDone: '恭喜達成存股目標！',
    shareGoalInputRequired: '請先輸入股票代碼與目標張數',
    shareGoalTypeOption: '存股張數目標',
    stockCodeName: '股票代碼/名稱',
    active: '股息統計',
    dividendStatsExcludedBadge: '不列入股息統計',
    avgPrice: '平均股價',
    totalQuantity: '總數量',
    actions: '操作',
    noInventory: '尚無庫存',
    sell: '賣出',
    transactionHistory: '交易歷史 ',
    showInventory: '顯示：目前庫存'
  },
  en: {
    importOverwrite: 'Import will overwrite existing records. Continue?',
    importDone: 'Import completed',
    exportCsvConfirm: 'Export CSV?',
    backupPrompt: 'It has been over 30 days since last backup. Export CSV backup?',
    inputRequired: 'Please enter all fields',
    invalidNumbers: 'Please enter valid numbers, price and date',
    confirmDeleteRecord: 'Delete this record?',
    sellExceeds: 'Sell quantity cannot exceed inventory',
    notice:
      'This is a free website, and to safeguard your privacy we never store your data on any backend or server. Every record—including your settings and activity history—lives only in your browser. Turn on auto-save to create device-side backups automatically. In short: your data stays on this computer, never uploads, and we never see it.',
    addRecord: 'Add Purchase',
    quickAdd: 'Quick Purchase',
    quickAddEmpty: 'No recent ETF purchases yet',
    quickAddTitle: 'Quick Add Purchases',
    quickAddNoPurchase: 'Buy',
    quickAddDate: 'Purchase Date',
    quickAddQuantity: 'Quantity',
    quickAddPrice: 'Price',
    quickAddSave: 'Save',
    quickAddClose: 'Close',
    quickAddSelectionSummary: 'Selected ETFs: {count}',
    quickAddCurrencyTwd: 'NT$',
    quickAddCurrencyUsd: 'US$',
    quickAddPlaceholderQuantity: 'Enter quantity',
    quickAddPlaceholderPrice: 'Enter price',
    dataAccess: 'Data Access',
    currentInventory: 'Inventory',
    showHistory: 'Show: Transaction',
    cache: 'Cache',
    stockCache: 'Stock list cache',
    dividendCache: 'Dividend cache',
    totalInvestment: 'Total Investment:',
    totalValue: 'Total Value:',
    investmentGoals: 'Expected Dividend Targets',
    goalNameLabel: 'Name your goal',
    goalNamePlaceholder: 'e.g. Build a $5K dividend stream',
    goalNameHelper: 'A memorable name keeps your motivation high.',
    goalFormIntro: 'Give your dividend plan a motivating title, then choose an annual, monthly, or minimum target.',
    goalCurrencyLabel: 'Currency',
    goalCurrencyTwd: 'New Taiwan Dollar (NT$)',
    goalCurrencyUsd: 'US Dollar (US$)',
    goalCashflowSectionTitle: 'Cash-flow goals',
    goalCashflowEmpty: 'No cash-flow goals yet. Click "Add cash-flow goal" to start.',
    goalCashflowAdd: 'Add cash-flow goal',
    goalCashflowRemove: 'Remove goal',
    goalTypeLabel: 'Choose goal type',
    annualGoal: 'Annual Goal',
    monthlyGoal: 'Monthly Goal',
    minimumGoal: 'Monthly Minimum Goal',
    goalDividendAccumulated: 'Accumulated dividends:',
    goalDividendMonthly: 'Average monthly dividends:',
    goalDividendMinimum: 'Monthly minimum dividends:',
    goalTargetAnnual: 'Annual target:',
    goalTargetMonthly: 'Monthly target:',
    goalTargetMinimum: 'Monthly minimum target:',
    goalText: 'My plan',
    goalSave: 'Save',
    goalSaved: 'Plan updated—keep going!',
    goalSavedEmpty: 'Set your goal to get started!',
    goalEmpty: 'No plan yet—give your dividend goal a name and add annual and monthly targets below to stay focused.',
    goalInputPlaceholderTotal: 'e.g. 5000',
    goalInputPlaceholderMonthly: 'e.g. 500',
    goalFormShow: 'Add or edit goal',
    goalFormHide: 'Hide goal form',
    goalAnnualHalf: 'Halfway through the year—your dream cashflow is getting closer!',
    goalAnnualDone: 'Annual goal achieved! Keep that momentum building income!',
    goalMonthlyHalf: 'Over halfway this month—one more push!',
    goalMonthlyDone: 'Monthly goal achieved—stay in this winning rhythm!',
    goalMinimumHalf: 'Over halfway this month—one minimum more push!',
    goalMinimumDone: 'Monthly minimum goal achieved—stay in this winning rhythm!',
    goalDividendYtdLabel: 'Accumulated dividends',
    goalDividendAnnualLabel: 'Annual dividends',
    goalDividendMonthlyLabel: 'Average monthly dividends',
    goalDividendMinimumLabel: 'Monthly minimum dividends',
    goalAchievementLabel: 'Achievement',
    shareGoalSectionTitle: 'Share accumulation targets',
    shareGoalEmptyList: 'No share targets yet—enter a ticker and target lots, then click "Add share target."',
    shareGoalStockInputLabel: 'Ticker / Name',
    shareGoalStockInputPlaceholder: 'e.g. 0056 High Dividend ETF',
    shareGoalTargetLabelForm: 'Target lots',
    shareGoalTargetPlaceholder: 'e.g. 100',
    shareGoalAddButton: 'Add share target',
    shareGoalRemove: 'Remove',
    shareGoalUnit: 'lots',
    shareGoalCurrent: 'Current lots:',
    shareGoalTargetDisplay: 'Target lots:',
    shareGoalHalf: 'Over halfway there—keep it up!',
    shareGoalDone: 'Share target reached—great job!',
    shareGoalInputRequired: 'Enter a ticker and target lots first.',
    shareGoalTypeOption: 'Share accumulation target',
    stockCodeName: 'Stock Code/Name',
    active: 'Dividend stats',
    dividendStatsExcludedBadge: 'Excluded from dividend stats',
    avgPrice: 'Average Price',
    totalQuantity: 'Total Quantity',
    actions: 'Actions',
    noInventory: 'No inventory',
    sell: 'Sell',
    transactionHistory: 'Transaction ',
    showInventory: 'Show: Inventory'
  }
};

export default inventoryTabText;
