# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Install Node and set up pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Enable pnpm via Corepack (ensures pnpm is on PATH)
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: true

      # 4. Install dependencies
      - run: pnpm install

      # 5. (Optional) Build your project
      - run: pnpm run build

      # 6. Run tests or other steps
      - run: pnpm test
