name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: etf_react_server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: etf_react_server/pnpm-lock.yaml

      - name: Enable Corepack (use pnpm version from package.json)
        run: corepack enable

      - name: Setup pnpm (no explicit version here)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install deps (lockfile-aware)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install --no-frozen-lockfile
          fi

      - name: Build
        run: pnpm build

      - name: Test (optional)
        run: pnpm test --if-present
